name: Kotlin CI with Gradle
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: 获取信息
        uses: actions/checkout@v3
      - name: 安装JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 标记gradlew为可执行
        run: chmod +x ./gradlew
      - name: 验证 Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 执行 Gradle 测试
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: test
#      - name: 执行 Gradle 构建
#        uses: gradle/gradle-build-action@v2.2.2
#        with:
#          arguments: build
      - name: 发布包
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ secrets.OSSRH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
