name: 发布包到 GitHub
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 标记gradlew为可执行
        run: chmod +x ./gradlew
      - name: 验证 Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 执行 Gradle 构建
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: build
      - name: 发布包
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGE_TOKEN }}
